#!/bin/bash
total 20
-rwxr--r-- 1 root root 16 Feb  9 06:49 0-current_working_directory
-rw-r--r-- 1 root root 16 Feb  9 06:45 0x00-shell_basic
-rwxr--r-- 1 root root 68 Feb  9 08:54 1-listit
-rwxr--r-- 1 root root 21 Feb  9 08:44 2-bring_me_home
-rw-r--r-- 1 root root  0 Feb  9 11:09 3-listfiles
-rw-r--r-- 1 root root 41 Feb  9 06:53 README.md
